---
title: "WGCNA Section 5: Network visualization using WGCNA functions"
author: "Angela Yoder"
date: "`r Sys.Date()`"
---

**The goals of this program are:**

1. Visualize relationship between modules and phenotype

```{r, echo = F, results = 'hide', message = F, warning = F}
# Data input

# set working directory
setwd("C:/Users/angel/OneDrive/Desktop/Saba Lab/Data/")

# upload data
phen = read.csv("Phenotype_WGCNA.csv")
protein_brain = read.csv("Brain_WGCNA.csv")
moduleColors= read.csv("moduleColors_block_WGCNA.csv")
chosenModules = read.csv("Chosen Modules.csv")

# fix problems
moduleColors = moduleColors[,2]
names = protein_brain[,1]
protein_brain = protein_brain[,2:dim(protein_brain)[2]]
rownames(protein_brain) = names

names = phen[,1]
phen = phen[,2:5]
rownames(phen) = names 

library(WGCNA)
library(tidyverse)
nGenes = ncol(protein_brain)

auc1_names = read.csv("AUC1 Module Names.csv")
auc2_names = read.csv("AUC2 Module Names.csv")
et2_names = read.csv("EtOH Week 2.csv")
et3_names = read.csv("EtOH Week 3.csv")

auc1_names = auc1_names[,2]
auc2_names = auc2_names[,2]
et2_names = et2_names[,2]
et3_names = et3_names[,2]

removeME = function(x)
{
  ret = c()
  for (i in x)
  {
  b = sub("ME", "", i)
  ret = c(ret, b)
  }
  return(ret)
}

#auc1_names = removeME(auc1_names)
#auc2_names = removeME(auc2_names)
#et2_names = removeME(et2_names)
#et3_names = removeME(et3_names)

```


```{r}
# Recalculate module eigengenes
MEs = moduleEigengenes(protein_brain, moduleColors)$eigengenes
### auc1

# Eigengenes related to auc1

MEs_auc1 = MEs[, auc1_names]

# Isolate weight from the clinical traits
auc1 = as.data.frame(phen$meanauc1gkg);
names(auc1) = "auc1"
# Add the weight to existing module eigengenes
MET = orderMEs(cbind(MEs_auc1, auc1))
# Plot the relationships among the eigengenes and the trait
#sizeGrWindow(5,7.5);
par(cex = 0.5)
plotEigengeneNetworks(MET, "", marDendro = c(0,4,1,2), marHeatmap = c(3,4,1,2), cex.lab = 0.8, xLabelsAngle
= 90, signed = FALSE)

### auc2

# Eigengenes related to auc1

MEs_auc2 = MEs[, auc2_names]

# Isolate weight from the clinical traits
auc2 = as.data.frame(phen$meanauc2gkg);
names(auc2) = "auc2"
# Add the weight to existing module eigengenes
MET = orderMEs(cbind(MEs_auc2, auc2))
# Plot the relationships among the eigengenes and the trait
#sizeGrWindow(5,7.5);
par(cex = 0.5)
plotEigengeneNetworks(MET, "", marDendro = c(0,4,1,2), marHeatmap = c(3,4,1,2), cex.lab = 0.8, xLabelsAngle
= 90, signed = FALSE)

### Etwk2

# Eigengenes related to auc1

MEs_et2 = MEs[, et2_names]

# Isolate weight from the clinical traits
et2 = as.data.frame(phen$EtOHing_wk2);
names(et2) = "et2"
# Add the weight to existing module eigengenes
MET = orderMEs(cbind(MEs_et2, et2))
# Plot the relationships among the eigengenes and the trait
#sizeGrWindow(5,7.5);
par(cex = 0.5)
plotEigengeneNetworks(MET, "", marDendro = c(0,4,1,2), marHeatmap = c(3,4,1,2), cex.lab = 0.8, xLabelsAngle
= 90, signed = FALSE)

### Etwk3

# Eigengenes related to auc1

MEs_et3 = MEs[, et3_names]

# Isolate weight from the clinical traits
et3 = as.data.frame(phen$EtOHing_wk3);
names(et3) = "et3"
# Add the weight to existing module eigengenes
MET = orderMEs(cbind(MEs_et3, et3))
# Plot the relationships among the eigengenes and the trait
#sizeGrWindow(5,7.5);
par(cex = 0.5)
plotEigengeneNetworks(MET, "", marDendro = c(0,4,1,2), marHeatmap = c(3,4,1,2), cex.lab = 0.8, xLabelsAngle
= 90, signed = FALSE)
```

```{r, echo = F, fig.show = 'hide'}
# Plot the dendrogram
#sizeGrWindow(6,6);
par(cex = 0.8)
plotEigengeneNetworks(MET, "Eigengene dendrogram", marDendro = c(0,4,2,0),
plotHeatmaps = FALSE)
# Plot the heatmap matrix (note: this plot will overwrite the dendrogram plot)
par(cex = 1.0)
plotEigengeneNetworks(MET, "Eigengene adjacency heatmap", marHeatmap = c(3,4,2,2),
plotDendrograms = FALSE, xLabelsAngle = 90)


```