---
title: "WGCNA Section 2b: Step-by-step network construction and module detection"
author: "Angela Yoder"
date: "`r Sys.Date()`"
---

**The goals of this program are:**

1. Choose Soft Thresholding level
2. Detect and label modules

```{r}
# Data input

# set working directory
setwd("C:/Users/angel/OneDrive/Desktop/Saba Lab/Data/")

#phen = read.csv("Phenotype_WGCNA.csv")
protein_brain = read.csv("Brain_WGCNA.csv")

names = protein_brain[,1]
protein_brain = protein_brain[,2:dim(protein_brain)[2]]
rownames(protein_brain) = names

#names = phen[,1]
#phen = phen[,2:5]
#rownames(phen) = names

library(WGCNA)
library(tidyverse)
#library(biomaRt)

```

Min module size want to be 5. blockwiseConsensusModules: deepsplit - 4

```{r}
# Choose a set of soft-thresholding powers

powers = c(c(1:10), seq(from = 12, to=20, by=2))
# Call the network topology analysis function
sft = pickSoftThreshold(protein_brain, powerVector = powers, verbose = 5) ## expression data
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h; use 0.8 to 0.95
abline(h=0.80,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")

```

Soft threshold power decided to be 8

More modules than colors in base R- used minModuleSize of 15 instead of 5

```{r}

softPower = 8
adjacency = adjacency(protein_brain, power = softPower)

TOM = TOMsimilarity(adjacency);
dissTOM = 1 - TOM

geneTree = hclust(as.dist(dissTOM), method = "average")
plot(geneTree, labels = FALSE)

# We like large modules, so we set the minimum module size relatively high:
minModuleSize = 15;
# Module identification using dynamic tree cut:
dynamicMods = cutreeDynamic(dendro = geneTree, distM = dissTOM,
deepSplit = 4, pamRespectsDendro = FALSE,
minClusterSize = minModuleSize);
#table(dynamicMods)

# Convert numeric lables into colors
colors = sample(colors(), size = length(unique(dynamicMods)))
dynamicColors = labels2colors(dynamicMods, colorSeq = colors)
table(dynamicColors)
# Plot the dendrogram and colors underneath
sizeGrWindow(8,6)
plotDendroAndColors(geneTree, dynamicColors, "Dynamic Tree Cut",
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05,
main = "Gene dendrogram and module colors")

```

```{r}
# Calculate eigengenes
MEList = moduleEigengenes(protein_brain, colors = dynamicColors)
MEs = MEList$eigengenes
# Calculate dissimilarity of module eigengenes
MEDiss = 1-cor(MEs);
# Cluster module eigengenes
METree = hclust(as.dist(MEDiss), method = "average");
# Plot the result
sizeGrWindow(7, 6)
plot(METree, main = "Clustering of module eigengenes",
xlab = "", sub = "")

MEDissThres = 0.25
# Plot the cut line into the dendrogram
abline(h=MEDissThres, col = "red")
# Call an automatic merging function
merge = mergeCloseModules(protein_brain, dynamicColors, cutHeight = MEDissThres, verbose = 3)
# The merged module colors
mergedColors = merge$colors;
# Eigengenes of the new merged modules:
mergedMEs = merge$newMEs;
sizeGrWindow(12, 9)
#pdf(file = "Plots/geneDendro-3.pdf", wi = 9, he = 6)
plotDendroAndColors(geneTree, cbind(dynamicColors, mergedColors),
c("Dynamic Tree Cut", "Merged dynamic"),
dendroLabels = FALSE, hang = 0.03,
addGuide = TRUE, guideHang = 0.05)
#dev.off()

# Rename to moduleColors
moduleColors = mergedColors
# Construct numerical labels corresponding to the colors
colorOrder = c("grey", standardColors(50));
moduleLabels = match(moduleColors, colorOrder)-1;
MEs = mergedMEs

```

```{r}
# Export

setwd("C:/Users/angel/OneDrive/Desktop/Saba Lab/Data")
write.csv(moduleColors, "moduleColors_WGC NA.csv")


```