---
title: "WGCNA Section 2c: Dealing with large data sets: block-wise network construction and
consensus module detection"
author: "Angela Yoder"
date: "`r Sys.Date()`"
---

**The goals of this program are:**

1. Choose Soft Thresholding level
2. Detect and label modules via blockwise modules

```{r}
# Data input

# set working directory
setwd("C:/Users/angel/OneDrive/Desktop/Saba Lab/Data/")

#phen = read.csv("Phenotype_WGCNA.csv")
protein_brain = read.csv("Brain_WGCNA.csv")

names = protein_brain[,1]
protein_brain = protein_brain[,2:dim(protein_brain)[2]]
rownames(protein_brain) = names

#names = phen[,1]
#phen = phen[,2:5]
#rownames(phen) = names

library(WGCNA)
library(tidyverse)
#library(biomaRt)

```

Min module size want to be 5. blockwiseConsensusModules: deepsplit - 4


```{r, echo = F}
# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))
# Call the network topology analysis function
sft = pickSoftThreshold(protein_brain, powerVector = powers, verbose = 5)
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft$fitIndices[,1], -sign(sft$fitIndices[,3])*sft$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponds to using an R^2 cut-off of h
abline(h=0.90,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft$fitIndices[,1], sft$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft$fitIndices[,1], sft$fitIndices[,5], labels=powers, cex=cex1,col="red")



```

Soft threshold power decided to be 8

Min module size want to be 5. blockwiseConsensusModules: deepsplit - 4

```{r}
# signed or unsigned? that is the question

softPower = 8
bwnet = blockwiseModules(protein_brain, 
  power = 8, TOMType = "signed", minModuleSize = 5,
  reassignThreshold = 0, mergeCutHeight = 0.25,
  numericLabels = TRUE,
  saveTOMs = TRUE,
  deepsplit = 4,
  saveTOMFileBase = "blockwiseTOM",
  verbose = 3)

moduleColors_block = labels2colors(bwnet$colors)


```


```{r}
# Export

setwd("C:/Users/angel/OneDrive/Desktop/Saba Lab/Data")
write.csv(moduleColors_block, "moduleColors_block_WGCNA.csv")

```